### ISSUE TITLE
Add IP Camera widget

### ISSUE THREAD

**Issue by genielabs** [genielabs/homegenie-plus-android#1]

**Comment by genielabs** [comment]
added in beta 1.0 rev 9.

**Comment by bitcraze1** [comment]
Hi, Gene

Great, been waiting on the Camera to be available in Plus.

Two questions:

1) When will Rev 9 be available on Android Playstore? Ver 8 still showing.
2) Why is the Plus version not showing in the usual Playstore, when one searches? Only free version available, then have to search Google and following the links.

Thanks,


Eugene
