### ISSUE TITLE
UI : optimize space (some idea)

### ISSUE THREAD

**Issue by noliono** [genielabs/homegenie-plus-android#13]
- Reduce the top bar with "HomeGenie", "preference", "voice control" and the name of the group.
- Very large widget for device, ... Above all with phone 
- Device information (not so useful or redundant) : Error, Level => Add a button (like HistoryLog one) to have this information

(see joint file for example)
![screenshot_2015-10-30-04-14-40](https://cloud.githubusercontent.com/assets/10108085/10837817/12640768-7ebe-11e5-8922-9aa7a8c28cdb.png)
![screenshot_2015-10-30-04-14-54](https://cloud.githubusercontent.com/assets/10108085/10837818/126bdb3c-7ebe-11e5-9109-03eacab88bba.png)

**Comment by genielabs** [comment]
hi nolio I've done some of your requests, but not all of them:
1) top bar space cannot be reduced as it is a standard (suggested by google) of 48dp
2) I didn't understand this, please explain better
3) ok I did it. The only issue is that currently only numeric values can have a log. Fields with string values won't show up in the log

**Comment by noliono** [comment]
Hi Gene,
Ok thanks. 
2/ it's my arrow from right to left in the 2 pictures. It could be nice to have more than one device on a line when the phone is in portrait mode...
1/ and have the name of group in the top bar ?
