### ISSUE TITLE
2 items Dashboard and switch indications

### ISSUE THREAD

**Issue by Acorlin** [genielabs/homegenie-plus-android#17]
Samsung Android phone v.5.0
Just downloaded new version. Has the same issues as the original.
In Dashboard just under the temperature reading in the town I specified the next line is cut in half. The portrait or landscape makes no difference.

Under my group "lights and switches" when I push a particular switch the correct action occurs but the state of the switch on the screen does not change. Same as original version.
Alan

**Comment by genielabs** [comment]
Can you provide a screenshot of the dashboard?
Does the state of the switch correctly update on the web user interface?
Is the led in the upper right (next to the groups navigation bar) of green color?

**Comment by Acorlin** [comment]
Screen shot from Acorlin #17.

**Comment by Acorlin** [comment]
The led is green. When program is first run the first toggle of any switch
shows up on the phone and the desktop. When trying the same or any other
switch again from the phone causes the correct action to take place and it
shows correctly on the desktop
The phone status does not change.

**Comment by Acorlin** [comment]
![screenshot_2015-10-31-17-25-47](https://cloud.githubusercontent.com/assets/15524690/10867419/284a2efc-801e-11e5-91fc-18353b966cec.png)

**Comment by genielabs** [comment]
Where is HG server running on? Please provide O.S., locale language and HG version. Can you also provide the log file from HG of a session where the error occurs?
Also read this:
http://www.homegenie.it/forum/index.php?topic=1141.msg6914#msg6914
could be a possible solution.

**Comment by Acorlin** [comment]
Gene...
The desktop is running the free version of HG. The latest version. It works
fine.
The errors I mentioned are the HG Plus latest version on my Samsung android
v5.0 phone. What is the log file called on a phone?
Alan

**Comment by genielabs** [comment]
Hi Arcorlin, 

the weather widget will be fixed for next beta release.
For the disconnection error: where have you installed HomeGenie server? Windows? Linux? Mac?

**Comment by Acorlin** [comment]
Windows 10.

**Comment by Acorlin** [comment]
At 11:14pm. my time I toggled the "Hallway" #18 lights on and off. The lights did turn on and off. The desktop running HG+ showed the status change. My android phone showed the first status change and then remained in the "on" position even though it did turn the lights on and off. I figured out how to get you the log. This setup is in a remote location and I am only on location twice a month or so.

**Comment by Acorlin** [comment]
Gene--
I could not upload the file as a csv without permission. Rename this jpg to .csv..
![homegenie_log_0](https://cloud.githubusercontent.com/assets/15524690/11014131/8bebff8e-84de-11e5-9c62-a0930596f4f6.jpg)

Alan

**Comment by genielabs** [comment]
hi @Acorlin ,
you're using an old version of HG server. Please install latest release (v1.1 r500):
http://genielabs.github.io/HomeGenie/download.html

**Comment by Acorlin** [comment]
Gene..
My backup would not restore with v 1.1 r500

I would have answered you on the hg+ hithub but I could not figure out how
to upload the .zip backup.
Alan

**Comment by genielabs** [comment]
it should have restored... what version of HG are you running? btw if you want to email me the backup use the address: gene at homegenie dot it. alternatively recreate your configuration from scratch.

**Comment by Acorlin** [comment]
I have also noticed I must touch the screen multiple times and very hard to activate a state change. When I go back to the original version with the on and off button I only need to barely touch the screen to initiate a state change.  Gave up trying to restore my backup with v1.1 r500. When I have time I will reconstruck.
