### ISSUE TITLE
Alarm Clock

### ISSUE THREAD

**Issue by guytpetj** [genielabs/homegenie-plus-android#24]
Add full screen clock/alarm clock function, including dimming of screen, multiple alarm times and snooze. This to aid small (7") tablets used with HG+ as controller in a bedroom.

Alarm clock should show very dim at nicht and except for time, shows the next alarm event time and has 4 buttons: alarm on/of, cancel alarm, snooze and Display HG interface.

**Comment by genielabs** [comment]
There will be a screen saver with clock and weather display (and some other infos), but I am not sure about the alarm since android devices already have built-in alarm functionality.
