### ISSUE TITLE
[Request] Dimmer slider for color lights

### ISSUE THREAD

**Issue by mvdarend** [genielabs/homegenie-plus-android#29]
One thing I'm missing from HomeGenie plus is the ability to quickly dim the colored lights (without having to 'reprogram' one of the preset buttons.) 

It would be great if you could have a slider under the colour selecter like the image in this forum post:
http://www.homegenie.it/forum/index.php?topic=1142.msg8048#msg8048

**Comment by genielabs** [comment]
did that, it will be available shortly in rev 17.
