### ISSUE TITLE
Add UPnP Media Browser widget

### ISSUE THREAD

**Issue by genielabs** [genielabs/homegenie-plus-android#3]

**Comment by bitcraze1** [comment]
Any updated on this one?

**Comment by genielabs** [comment]
it's coming with next app update (soon)

![selezione_601](https://cloud.githubusercontent.com/assets/6654265/11221051/5e2721ae-8d63-11e5-99ee-3832bdd458be.png)

![selezione_602](https://cloud.githubusercontent.com/assets/6654265/11221064/6b3a58f2-8d63-11e5-9e45-fa0b545c1d82.png)

**Comment by genielabs** [comment]
hg plus r13

**Comment by bitcraze1** [comment]
Have upgraded my App: Working well. Thanks so much, Gene!
