### ISSUE TITLE
Motion sensors are always active

### ISSUE THREAD

**Issue by skagmo** [genielabs/homegenie-plus-android#33]
How are motion sensors assumed to work? The Z-wave sensors I have used only sends an update when activity is detected ("MotionDetect" is set to 0xff), and it is never set back to "inactive". In Homegenie Plus, this results in a constantly blinking widget icon. As a workaround, I have made a program to set "MotionDetect" back to 0 after a given time of inactivity. Is this the way it is supposed to work, or should the app evaluate the time since last update while "MotionDetect" is always active?  https://github.com/skagmo/multitrx/blob/master/homegenie-addon/AutoClearMotion.hgx

**Comment by genielabs** [comment]
Yes, this is the way it is supposed to work. Usually sensors send a value when activated (255) and then when deactivated (0) after a certain time. This can be achieved by configuring the motion sensor device properly.
