### ISSUE TITLE
BUG - Screen saver needs at least one picture in the gallery

### ISSUE THREAD

**Issue by guytpetj** [genielabs/homegenie-plus-android#35]
HG Plus will crash if you do not have at least one picture in your gallery when the new screen saver is active. 

I'm running HG Plus on a dedicated tablet which did not have pictures in the picture folder/gallery. 

Once I figured out what happened and added a picture to the folder HG Plus started working as expected.

**Comment by genielabs** [comment]
this is already fixed in r20.

**Comment by genielabs** [comment]
this is already fixed in r20.
